targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
      - test/**
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: schema.graphql
              queries_glob: graphql/*.graphql
              output: lib/graphql/graphql_api.dart