targets:
  $default:
    sources:
      - $package$
      - lib/**
      - graphql/**
      - schema.graphql
      - test/**
    builders:
      artemis:
        options:
          scalar_mapping:
            - graphql_type: DateTime
              dart_type: DateTime
            - graphql_type: GenericScalar
              dart_type: List
          schema_mapping:
            - schema: schema.graphql
              queries_glob: graphql/*.graphql
              output: lib/graphql/graphql_api.dart