# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '8.x'

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'dev' or 'beta'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate graphql
        run: flutter pub run build_runner build

      - name: Check code formatting
        run: flutter format -n --set-exit-if-changed .

      - name: Run Flutter analyzer
        run: flutter analyze

      - name: Build app
        run: flutter build apk

      - name: Test app
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info

      - name: Upload built app
        uses: actions/upload-artifact@v2
        with:
          name: HomeKeeper.apk
          path: build\app\outputs\flutter-apk\app-release.apk
