name: Update

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  Update_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download new schema if alvaible
        shell: bash
        run: |
          set -x
          LATEST_BACKEND_ARTIFACT=$( \
            curl \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/MariuszBielecki288728/HomeKeeper-backend/actions/artifacts?per_page=1 \
            | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['archive_download_url'])")

          SCHEMA_ARCH="schema.zip"
          FIXED_SCHEMA_ARCH=fix_$SCHEMA_ARCH

          curl \
            -H "Accept: application/vnd.github.v3+json" \
            $LATEST_BACKEND_ARTIFACT \
            -L -o $SCHEMA_ARCH
          ls
          zip -FF $SCHEMA_ARCH --out $FIXED_SCHEMA_ARCH | unzip -d new_schema

          if ! diff schema.graphql new_schema/schema.graphql
          then
            echo "A newer scheme is not available"
            exit 1
          fi

          cat new_schema/schema.graphql > schema.graphql
          rm -rf new_schema $SCHEMA_ARCH $FIXED_SCHEMA_ARCH

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update schema
          title: Update schema
          branch: schema_update
