name: Update

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  Update_schema:
    runs-on: ubuntu-latest
    env:
      NEW_SCHEMA_ALVAIBLE: false
    steps:
      - uses: actions/checkout@v2
      - name: Download new schema if alvaible
        shell: bash
        run: |
          set -x
          LATEST_BACKEND_ARTIFACT=$( \
            curl \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/MariuszBielecki288728/HomeKeeper-backend/actions/artifacts?per_page=1 \
            | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['archive_download_url'])")

          SCHEMA_FILENAME="schema.zip"
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            $LATEST_BACKEND_ARTIFACT \
            -L -o $SCHEMA_FILENAME
          unzip $SCHEMA_FILENAME -d new_schema

          if ! diff -q --ignore-space-change --ignore-blank-lines schema.graphql new_schema/schema.graphql &> /dev/null
          then
            echo "A newer schema is not available"
          else
            echo "::set-env name=NEW_SCHEMA_ALVAIBLE::true"
          fi

          cat new_schema/schema.graphql > schema.graphql
          rm -rf new_schema $SCHEMA_FILENAME

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        if: ${{ env.NEW_SCHEMA_ALVAIBLE == 'true' }}
        with:
          commit-message: Update schema
          title: Update schema
          branch: schema_update
